paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - products
      responses:
        "200":
          description: Los productos fueron entregados exitosamente 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error en la conexion a la db
    post:
      summary: Crea un nuevo producto
      tags:
        - products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: El producto fue creado con exito 
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/Products"
        "500":
          description: Error en la conexion a la db
  /api/products/{id}:
    get:
      summary: Obtiene un producto
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id del producto deseado 
          schema:
            $type: String
      responses:
        "200":
          description: Producto encontrado
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Products"
    put:
      summary: Actualizar un producto a partir del ID
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: ID del producto que desea modificar 
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/updateProduct"
      responses:
        "200":
          description: Producto modificado exitosamente
          content:
            application/json:
              schema:
                $ref: "#components/schemas/Success"
components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: String
          description: success or error
        message:
          type: String
          description: aclarando que ocurrio
      example:
        status: success
        message: User updated
    Products:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID auto generado by mongo
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del producto
        thumbnails:
          type: String
          description: Fotos del producto
        status:
          type: Boolean
          description: Estado del producto
        code:
          type: String
          description: Codigo del producto
        category:
          type: String
          description: Categoria del producto
      example:
        _id: ObjectId("6489cd9ba9cf74d0e1377eac")
        name: Kramer Baretta
        description: Kramer Baretta Pappo's signature
        price: 11000
        stock: 10
        thumbnail: no image
        status: true
        code: papp2
        category: electric guitar
  requestBodies:
    updateProduct:
      type: object
      properties:
        name:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripcion del producto
        price:
          type: Number
          description: Precio del producto
        stock:
          type: Number
          description: Stock del producto
        thumbnails:
          type: String
          description: Fotos del producto
        status:
          type: Boolean
          description: Estado del producto
        code:
          type: String
          description: Codigo del producto
        category:
          type: String
          description: Categoria del producto
      example:
        _id: ObjectId("6489cd9ba9cf74d0e1377eac")
        name: Kramer Baretta
        description: Kramer Baretta Pappo's signature
        price: 11000
        stock: 10
        thumbnail: no image
        status: true
        code: papp2
        category: electric guitar